### ISSUE TITLE
rename repository to arcgis-to-geojson-utils?

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-to-geojson-utils#2]
it took me a bit to figure out that the npm package is actually `arcgis-to-geojson-utils`

at a bare minimum the readme title, `npm install` instructions, badge, code snippets, etc. need to be updated...

**Comment by jgravois** [comment]
mostly resolved by a338b6f

**Comment by patrickarlt** [comment]
I'll be able to do it once I get privileges from the GitHub Admin team.

**Comment by patrickarlt** [comment]
Done
