### ISSUE TITLE
add a CDN example to README

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-to-geojson-utils#29]
from https://github.com/Esri/arcgis-to-geojson-utils#usage

> This package is distributed as a UMD module and can also be used in AMD based systems or as a global under the `ArcgisToGeojsonUtils` namespace.

apparently the note above doesn't make it clear enough that you don't have to build the lib yourself. lets add a code snippet too.

ref: https://github.com/Esri/terraformer-arcgis-parser/issues/44#issuecomment-378343438

**Comment by hoogw** [comment]
Agree,  I am first time user, I don't know how to use this module in browser,  readme did not give any example how, only teach me how to use in node.js  

I end up use rollup.js bundle it by myself. Then @jgravois  suggest under dist/... already has bundled one.
