### ISSUE TITLE
How to convert arcgis featureSet to geojson?

### ISSUE THREAD

**Issue by hoogw** [Esri/arcgis-to-geojson-utils#30]
How to convert arcgis featureSet to geojson?

I understand this module only convert a single arcgis geometry to geojson, 

However, the response from arcgis rest api, are NOT geometry, 

instead, they are FeatureSet. 

Can you add the function to convert arcgis FeatureSet to geojson?

**Comment by jgravois** [comment]
> Can you add the function to convert arcgis FeatureSet to geojson?

as i explained in https://github.com/Esri/terraformer/issues/104#issuecomment-377396459, support for this is already present.

https://github.com/Esri/arcgis-to-geojson-utils/blob/ed3c56bd99acf73d454f3d6d09aba00bad373ce4/test/index.js#L1215-L1338

**Comment by hoogw** [comment]
Got it.  I just test, it works.  As I read, so far, terraformer   does NOT support feature collection, only this module does.
