### ISSUE TITLE
ArcGIS JSON structure is not getting formed

### ISSUE THREAD

**Issue by amrutab4** [Esri/arcgis-to-geojson-utils#31]
When I am generating ArcGIS JSON from any toolbox it will always have "features" and under that it will have "geometry" and attributes inside of it but this code is not doing that.
Also,  **"geometryType": "esriGeometryPolygon"** these are the geometry tyoe which are also not coming as a part of json. 
**Sample ESRI JSON format(generated from features to json toolbox in ArcMap) is as below:**
```json
{
    "displayFieldName": "",
    "features": [
        {
            "attributes": {
                "OBJECTID": 1,
                "OutlineComment": "testoutline",
                "ResourceID": "201",
                "SHAPE_Area": 0.006233100233813974,
                "SHAPE_Length": 0.4874967906258057
            },
            "geometry": {
                "rings": [
                    [
                        [
                            -73.58145436999996,
                            -36.33218832299997
                        ],
                        [
                            -73.52149838699995,
                            -36.295079320999946
                        ],
                        [
                            -73.55052137699994,
                            -36.353603471999975
                        ],
                        [
                            -73.52482963299997,
                            -36.43832287399994
                        ],
                        [
                            -73.58145436999996,
                            -36.394054308999955
                        ],
                        [
                            -73.59573113599998,
                            -36.37501862099998
                        ],
                        [
                            -73.65474820399999,
                            -36.398347928999954
                        ],
                        [
                            -73.60762844099997,
                            -36.336947244999976
                        ],
                        [
                            -73.58145436999996,
                            -36.33218832299997
                        ]
                    ]
                ]
            }
        }
    ],
    "fieldAliases": {
        "OBJECTID": "OBJECTID",
        "OutlineComment": "OutlineComment",
        "ResourceID": "ResourceID",
        "SHAPE_Area": "SHAPE_Area",
        "SHAPE_Length": "SHAPE_Length"
    },
    "fields": [
        {
            "alias": "OBJECTID",
            "name": "OBJECTID",
            "type": "esriFieldTypeOID"
        },
        {
            "alias": "ResourceID",
            "length": 50,
            "name": "ResourceID",
            "type": "esriFieldTypeString"
        },
        {
            "alias": "OutlineComment",
            "length": 50,
            "name": "OutlineComment",
            "type": "esriFieldTypeString"
        },
        {
            "alias": "SHAPE_Length",
            "name": "SHAPE_Length",
            "type": "esriFieldTypeDouble"
        },
        {
            "alias": "SHAPE_Area",
            "name": "SHAPE_Area",
            "type": "esriFieldTypeDouble"
        }
    ],
    "geometryType": "esriGeometryPolygon",
    "spatialReference": {
        "latestWkid": 4326,
        "wkid": 4326
    }
}
```

**Also following is the JSON which arcgis - to - geojson-utils is generating:**

![image](https://user-images.githubusercontent.com/38122484/38403131-da7ba8dc-397e-11e8-8df3-043396a82ca3.png)

**Comment by jgravois** [comment]
but when you run [Features to JSON](http://pro.arcgis.com/en/pro-app/tool-reference/conversion/features-to-json.htm), your input isn't GeoJSON, correct?

**Comment by amrutab4** [comment]
@jgravois  Obviously my input is not geojson, but the "esri JSON" which gets generated has "features" inside of it so that it can be easily used in arcGIS JS api to create and access featureset, graphic etc objects and loop through it! But when I am using JSON which is getting generated by 'arcgis-to-geojson-utils' I am not able to consume it in ArcGIS JS api  :( I am just wondering, what is the meaning of "ESRI JSON" then and what is the difference between normal JSON and ESRI JSON? Also, Geometry type will always come as "esripolygon"/"esriPoint" in any of the esri generated json. But this is not the case here as well.

**Comment by jgravois** [comment]
> what is the meaning of "ESRI JSON" then.

The Esri ecosystem includes an incredibly extensive open REST Specification that articulates what all sorts of different Esri JSON looks like. This JavaScript library is concerned specifically with converting back and forth between individual [ArcGIS Feature Objects](https://developers.arcgis.com/documentation/common-data-types/feature-object.htm) / [ArcGIS Geometry Objects](https://developers.arcgis.com/documentation/common-data-types/geometry-objects.htm) and the corresponding GeoJSON [Geometry](https://tools.ietf.org/html/rfc7946#section-3.1) and [Feature](https://tools.ietf.org/html/rfc7946#section-3.2) objects.

When you run **Features to JSON** in ArcGIS Desktop using _ArcGIS_ input data, [ArcGIS FeatureSet](https://developers.arcgis.com/documentation/common-data-types/featureset-object.htm) output is possible because metadata that describes field aliases, schema types and which field is used for display are available for the tool to introspect. 

This just isn't the case with GeoJSON. that is why we don't advertise [ArcGIS FeatureSet](https://developers.arcgis.com/documentation/common-data-types/featureset-object.htm) output as being available from this library.

> Geometry type will always come as "esripolygon"/"esriPoint" in any of the esri generated json. But this is not the case here as well.

I don't follow you here. can you elaborate?

**Comment by amrutab4** [comment]
@jgravois  
Hey Hi, 
Thank you so much for the prompt response! Yes I agree that ESRI includes vast REST specifications and you don't advertise featureset object either. 

Correct me if I am wrong here but I assumed that whatever 'ArcGIS JSON' will get generated from this utility will get consumed in ArcMap, Pro, ArcMap 10.5.1, might be in 'JSON to Features' tool? or I can pass that to ArcGIS REST API calls or ArcGIS JS API call? Is my assumption correct or not?

About Geometry type, When you give any geojson as an input to the function "geojsonToArcGIS" in index.js, there is this case called "polygon" which fetches the rings because of it's geojso.type = 
polygon' I think this polygon should be part of the response as "geometryType: "esriPolygon" as this is identifiable by ArcGIS. Let me know your thoughts about it?

 Additionally, I have made few (not so good) changes in the function 'geojsonToArcGIS' to explain what should be the output. I am focusing on passing polygon geojson. Pleasse take a look at the below function for more idea:

```js
 var ft = new Array();
 
 function geojsonToArcGIS (geojson, idAttribute) {
  idAttribute = idAttribute || 'OBJECTID';
  var spatialReference = { wkid: 4326 };
 // var geomType = "esriGeometry" + geojson.type;
  var result = {};
  var i;
 
  switch (geojson.type) {
    case 'Point':
      result.x = geojson.coordinates[0];
      result.y = geojson.coordinates[1];
      result.spatialReference = spatialReference;
      break;
    case 'MultiPoint':
      result.points = geojson.coordinates.slice(0);
      result.spatialReference = spatialReference;
      break;
    case 'LineString':
      result.paths = [geojson.coordinates.slice(0)];
      result.spatialReference = spatialReference;
      break;
    case 'MultiLineString':
      result.paths = geojson.coordinates.slice(0);
      result.spatialReference = spatialReference;
      break;
      case 'Polygon':
         
          ft.rings = orientRings(geojson.coordinates.slice(0));
         // result.features.geometry.rings = ft.rings;
          // result.spatialReference = spatialReference;
         // result.geometryType = geomType;
         
      break;
    case 'MultiPolygon':
      result.rings = flattenMultiPolygonRings(geojson.coordinates.slice(0));
      result.spatialReference = spatialReference;
      break;
      case 'Feature':
          if (geojson.geometry) {
              result.spatialReference = spatialReference;
              result.geometryType = "esriGeometry" + geojson.geometry.type;
             
              ft.geometry = geojsonToArcGIS(geojson.geometry, idAttribute);
              ft["geometry"].rings = ft["rings"];
              delete ft.rings;
             ft.attributes = (geojson.properties) ? shallowClone(geojson.properties) : {};
             
             
          }
         
          if (geojson.id) {
              ft.attributes[idAttribute] = geojson.id;
          }
          result["features"] = ft;
          result["features"].push(ft);
          break;
    case 'FeatureCollection':
        result = [];
        for (i = 0; i < geojson.features.length; i++) {
           // result.push(geojsonToArcGIS(geojson.features[i], idAttribute));
            result = geojsonToArcGIS(geojson.features[i], idAttribute);
        }
      break;
    case 'GeometryCollection':
      result = [];
      for (i = 0; i < geojson.geometries.length; i++) {
          result.push(geojsonToArcGIS(geojson.geometries[i], idAttribute));
      }
      break;
  }
  
  return result;
} 
```

I have one more query, I want to convert geojson to arcgis json and I should be able to consume that json in ArcMap 10.5.1 as well as in ArcGIS JS api to create features and graphics so I was looking forward to using this 'arcgis-to-geojson-utils' and as it is licensed under ESRI 2018 so wondering If I am at the right place or if you can suggest me any other library?

Looking forward to your response.

Thanks!

**Comment by jgravois** [comment]
> 'ArcGIS JSON' generated from this utility will get consumed in ArcMap, Pro, ArcMap 10.5.1, might be in 'JSON to Features' tool?

I'm not really sure what the most popular locations of consumption for output from this library are. that said, [JSON to Features](http://pro.arcgis.com/en/pro-app/tool-reference/conversion/json-to-features.htm) expects ArcGIS FeatureSet input and this library does **not** output that.

> I think this polygon should be part of the response as `geometryType: "esriGeometryPolygon"`. Let me know your thoughts about it?

I see what you're getting at now, but your current approach appends the `type` to each _individual feature_ within the collection, which isn't valid. and it looks like your previous attempt was to check the `type` of the FeatureCollection itself, which it appears you already realized won't work either.

you could certainly refactor your own forked code to check the `type` of individual features and use the information to set the type for the entire collection, but i don't plan on incorporating a change like that in this library for the simple reason that it is valid for a GeoJSON FeatureCollection to include mixed geometry types.

> wondering if I am at the right place or if you can suggest me any other library?

you _are_ in the right place, but instead of what you've been doing, you should try to build up a FeatureSet of your own _around_ the output of the lib if that's what you need.

```js
let featureSet = {
  "geometryType": "esriGeometryPolygon",
  "features": null
  // etc. 
}

featureSet.features = geojsonToArcGIS(featureCollection);
```

**Comment by amrutab4** [comment]
@jgravois  Thank you so much for your valuable suggestions. I will surely try what your mentioned! :)
