### ISSUE TITLE
browser tests are failing on travis

### ISSUE THREAD

**Issue by jgravois** [Esri/arcgis-to-geojson-utils#5]
```
not ok 1 no plan found
not ok 2 no assertions found
```

see https://travis-ci.org/Esri/arcgis-to-geojson-utils/jobs/99338506

the error is the same as i saw locally prior to adding  `babelify --presets es2015` to the test script.

the same thing is happening to leaflet-virtual-grid
https://travis-ci.org/patrickarlt/leaflet-virtual-grid/builds/99176458

i feel like we need to configure another travis pre-install or configuration option, i just don't know what.

**Comment by jgravois** [comment]
the badge url needs updated too.

**Comment by patrickarlt** [comment]
Passing now. You have to add `--browser phantom` to the `tape-run` command since Travis CI doesn't have electron installed.
