### ISSUE TITLE
Unexpected difference from Terraformer Parser

### ISSUE THREAD

**Issue by dmfenton** [Esri/arcgis-to-geojson-utils#8]
I am not sure what you want to do with this information, but in switching from Terraformer Parser I ran into the following unexpected change:

For this feature: 

```
{
  "attributes": {
    "PROJ_DESC": "REMODEL FOR DRINK STATION ON FLOOR 3. C/C                         "
  },
  "geometry": {
    "x": "NaN",
    "y": "NaN"
  }
}
```

[Found in the wild](http://mycity.houstontx.gov/arcgisv91/rest/services/PD/Permits_wm_Bldg/MapServer/2/query?where=OBJECTID%3D562288&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&returnTrueCurves=false&resultOffset=&resultRecordCount=&f=pjson)

Terraformer parser returns `[Error: Unknown type: undefined]`
Whereas this module returns `{}`

I know these are separate projects, but I thought you might want to be aware of this difference.

**Comment by jgravois** [comment]
which behavior seems more appropriate to you?  i'd argue we should output valid [GeoJSON](http://geojson.org/geojson-spec.html#feature-objects).

> A feature object must have a member with the name `"geometry"`. The value of the geometry member is a geometry object as defined above or a JSON null value

``` js
{
  "properties": {
    "PROJ_DESC": "REMODEL FOR DRINK STATION ON FLOOR 3. C/C                         "
  },
  "geometry": null
}
```

**Comment by dmfenton** [comment]
Returning `null` is a lot better than status quo
